catalog/urls.py
from django.urls import path
from catalog.views import (index,
                        LiteraryFormatListView,
                        BookListView,
                        AuthorListView,
                        BookDetailView,
                        BookCreateView,
                        BookUpdateView,
                        test_session_view,
                        AuthorCreateView,
                        LiteraryFormatCreateView,
                        LiteraryFormatUpdateView,
                        LiteraryFormatDeleteView,
                           )# person_create_view

app_name = "catalog"


urlpatterns = [
        path("", index, name="index"),
        path("literary-formats/", LiteraryFormatListView.as_view(), name="literary-formats-list"),
        path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name="literary-formats-create"),
        path("literary-formats/<int:pk>/update/", LiteraryFormatUpdateView.as_view(), name="literary-formats-update"),
        path("literary-formats/<int:pk>/delete/", LiteraryFormatDeleteView.as_view(), name="literary-formats-delete"),
        path("books/", BookListView.as_view(), name="book-list"),
        path("books/create", BookCreateView.as_view(), name="book-create"),
        path("books/<int:pk>/update/", BookUpdateView.as_view(), name="book-update"),
        path("authors/", AuthorListView.as_view(), name="author-list"),
        path("books/<int:pk>/", BookDetailView.as_view(), name="book_detail"),
        path("test-session/", test_session_view, name="test-session"),
        path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
]

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
    <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}">Prev</a></li>
      {% endif %}
    <li class="page-item active"><span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">Next</a></li>
    {% endif %}
    </ul>
  {% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
  <li class="list-group-item">
    Username: {{ user.username }}
    {% else %}
    <a href="{% url 'login' %}">Log in</a>
  </li>
  {% endif %}
  <br>
  {% if user.is_authenticated %}
  <li class="list-group-item">
    <a href="{% url 'logout' %}">Log out</a>
  </li>
  {% endif %}
  <br>
  <li class="list-group-item">
    <a href="{% url 'catalog:index' %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href={% url 'catalog:author-list' %}>All authors</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'catalog:book-list' %}">All books</a>
  </li>
  <li class="list-group-item">
    <a href={% url 'catalog:literary-formats-list' %}>All literary formats</a>
  </li>
</ul>