catalog/urls.py
from django.urls import path
from catalog.views import (index,
                        LiteraryFormatListView,
                        BookListView,
                        AuthorListView,
                        BookDetailView,
                        BookCreateView,
                        BookUpdateView,
                        test_session_view,
                        AuthorCreateView,
                        LiteraryFormatCreateView,
                        LiteraryFormatUpdateView,
                        LiteraryFormatDeleteView,
                           )# person_create_view

app_name = "catalog"


urlpatterns = [
        path("", index, name="index"),
        path("literary-formats/", LiteraryFormatListView.as_view(), name="literary-formats-list"),
        path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name="literary-formats-create"),
        path("literary-formats/<int:pk>/update/", LiteraryFormatUpdateView.as_view(), name="literary-formats-update"),
        path("literary-formats/<int:pk>/delete/", LiteraryFormatDeleteView.as_view(), name="literary-formats-delete"),
        path("books/", BookListView.as_view(), name="book-list"),
        path("books/create", BookCreateView.as_view(), name="book-create"),
        path("books/<int:pk>/update/", BookUpdateView.as_view(), name="book-update"),
        path("authors/", AuthorListView.as_view(), name="author-list"),
        path("books/<int:pk>/", BookDetailView.as_view(), name="book_detail"),
        path("test-session/", test_session_view, name="test-session"),
        path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
]

catalog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class LiteraryFormat(models.Model):
    objects = None
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name


class Author(AbstractUser):
    pseudonym = models.CharField(max_length=63, null=True, blank=True)
    class Meta:
        ordering = ("username", )

    def __str__(self):
        return f"{self.username}: {self.first_name} {self.last_name}"


class Book(models.Model):
    title = models.CharField(max_length=100)
    price = models.DecimalField(decimal_places=2, max_digits=7)
    format = models.ForeignKey(LiteraryFormat, on_delete=models.CASCADE, related_name="books")
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="books")

    class Meta:
        ordering = ("title", )

    def __str__(self):
        return f"Title {self.title}: price: {self.price}, format: {self.format}"

    def get_absolute_url(self):
        return reverse("catalog:book_detail", args=[str(self.id)])

catalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from catalog.models import Author, LiteraryFormat, Book


class AuthorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Author
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "pseudonym")


class BookForm(forms.ModelForm):
    authors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    class Meta(forms.ModelForm):
        model = Book
        fields = "__all__"


class LiteraryForm(forms.ModelForm):
    class Meta:
        model = LiteraryFormat
        fields = ["name"]


class BookSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "Search by Title"}),
        label="",
    )

catalog/views.py
from django.views import generic
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from catalog.forms import AuthorCreationForm, LiteraryForm, BookForm, BookSearchForm
from catalog.models import Book, Author, LiteraryFormat



def index(request: HttpRequest) -> HttpResponse:
    num_books = Book.objects.count()
    num_authors = Author.objects.count()
    num_literary_formats = LiteraryFormat.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {"num_books": num_books,
               "num_authors": num_authors,
               "num_literary_formats": num_literary_formats,
               "num_visits": num_visits,}

    return render(request,
                  "catalog/index.html",
                  context=context)


class LiteraryFormatListView(LoginRequiredMixin, generic.ListView):
    model = LiteraryFormat
    template_name = "catalog/literary_formats_list.html"
    context_object_name = "literary_formats_list"
    #queryset = LiteraryFormat.objects.filter()


# def literary_format_list_view(request: HttpRequest) -> HttpResponse:
#     literary_formats_list = LiteraryFormat.objects.all()
#     context = {"literary_formats_list": literary_formats_list}
#     return render(request, "catalog/literary_formats_list.html", context=context)

class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context['search_form'] = BookSearchForm(
            initial={"title": title},
        )
        return context

    # def get_queryset(self):
    #     title = self.request.GET.get("title")
    #     if title:
    #         return self.queryset.filter(title__icontains=title)
    #     else:
    #         return self.queryset
#OR
    def get_queryset(self):
        queryset = Book.objects.select_related("format")
        form = BookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains = form.cleaned_data['title'])
        else:
            return queryset

class AuthorListView(generic.ListView):
    model = Author


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


# def book_detail_view(request: HttpRequest, pk: int) -> HttpResponse:
#     try:
#         book = Book.objects.get(pk=pk)
#     except Book.DoesNotExist:
#         raise Http404("Book does not exist")
#
#     context = {"book": book}
#     return render(request, "catalog/book_detail.html", context=context)
def test_session_view(request: HttpRequest) -> HttpResponse:
    return HttpResponse(
        "<h1>Test Session View</h1>"
        f"<h4>Session data: {request.session['book']} </h4>"
    )


class AuthorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Author
    form_class = AuthorCreationForm
    # success_url = reverse_lazy("catalog:author-list")
    # template_name = "catalog/author_form.html"
# def person_create_view(request: HttpRequest) -> HttpResponse:
#     context = {}
#     form = AuthorForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         # Author.objects.create(**form.cleaned_data)
#         return HttpResponseRedirect(reverse("catalog:author-list"))
#     context["form"] = form
#     return render(request, "catalog/author_form.html", context=context)

    # if request.method == "GET":
    #     context = {
    #         "form": AuthorForm()
    #     }
    #     return render(request, "catalog/author_form.html", context=context)
    # elif request.method == "POST":
    #     form = AuthorForm(request.POST)
    #     if form.is_valid():
    #         Author.objects.create(**form.cleaned_data)
    #         return HttpResponseRedirect(reverse("catalog:author-list"))
    #     context ={
    #         "form": form
    #         }
    #     return render(request, "catalog/author_form.html", context=context)

class LiteraryFormatCreateView(LoginRequiredMixin, generic.CreateView):
    model = LiteraryFormat
    form_class = LiteraryForm
    success_url = reverse_lazy("catalog:literary-formats-list")
    template_name = "catalog/literary_format_form.html"

class LiteraryFormatUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = LiteraryFormat
    form_class = LiteraryForm
    success_url = reverse_lazy("catalog:literary-formats-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = LiteraryFormat
    success_url = reverse_lazy("catalog:literary-formats-list")
    template_name = "catalog/literary_format_confirm_delete.html"


class BookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Book
    form_class = BookForm

class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    form_class = BookForm

templates/catalog/author_form.html
{% extends "base.html" %}
{% block content %}
  <h1>Create Author</h1>
  <form action="" method="post" novalidate>
  {% csrf_token %}
    {{ form.as_p }}
    <br>
    <input type="submit" value="Enter">
  </form>
{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}
{% block content %}
  <h1 class="d-flex justify-content-between align-items-center">Author list 
    <a href="{% url 'catalog:author-create' %}" class="btn btn-primary"
  >+</a></h1>
  {% if author_list %}
    <table class="table">
    <tr>
      <th>ID</th>
      <th>Full name</th>
      <th>Username</th>
      <th>Pseudonym</th>
    </tr>
    {% for author in author_list %}
    <tr>
      <td>
        <a href="{{ author.get_absolute_url }}">{{ author.id }}</a></td>
      <td>{{ author.first_name }} {{ author.last_name }}</td>
      <td>{{ author.username }}</td>
      <td>{{ author.pseudonym|default_if_none:"" }}</td>
    </tr>
    {% endfor %}
    </table>
  {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Title: {{ book.title }} <a class="btn btn-secondary" href="{% url 'catalog:book-update' pk=book.id %}">Update</a></h1>
  <p><strong>Price: </strong>{{ book.price }}</p>
  <p><strong>Format: </strong>{{ book.format }}</p>
  <div class="ml-3">
  <h3>Authors</h3>
  {% for author in book.authors.all %}
    <hr>
    <p class="text-muted">{{ author.id }}</p>
    <p>{{ author.first_name }} {{ author.last_name }}</p>
    {% if author.pseudonym %}
    <p>{{ author.pseudonym }}</p>
    {% endif %}
    {% empty %}
    <p>No authors</p>
  {% endfor %}
  </div>
{% endblock %}

templates/catalog/book_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Book</h1>
  <form action="" method="post" novalidate>
  {% csrf_token %}
    {{ form|crispy}}
    <input class="btn btn-primary" type="submit" value="Enter">
  </form>
{% endblock %}

templates/catalog/book_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="d-flex justify-content-between align-items-center">Book list
  <a class="btn btn-primary" href="{% url 'catalog:book-create' %}">+</a></h1>
  <form method = "get" action="" class="form-inline">
  {{ search_form|crispy }}
    <input class= "btn btn-secondary" type="submit" name="search" value="📖">
  </form>
  {%  if book_list %}
   <table class="table">
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Format</th>
      <th>Price</th>
    </tr>
    {% for book in book_list %}
    <tr>
      <td>
        <a href="{{ book.get_absolute_url }}">{{ book.id }}</a></td>
      <td>{{ book.title }}</td>
      <td>{{ book.format|default_if_none:"" }}</td>
      <td>{{ book.price|default_if_none:"" }}</td>
    </tr>
    {% endfor %}
    </table>
  {% endif %}
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}
{% block title %}
  <title>Home page</title>
{% endblock %}
{% block content %}
  <h1>Library Home</h1>
  <p>Welcome to library!</p>
  <h3>Library content:</h3>
  <ul>
    <li>Num books: {{ num_books }}</li>
    <li>Num authors: {{ num_authors }}</li>
    <li>Num literary formats: {{ num_literary_formats }}</li>
  </ul>
  <p>You have visited this page {{ num_visits }} time {{ num_visits|pluralize }}</p>
{% endblock %}

templates/catalog/literary_format_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>Delete Literary Format</h1>
  <p>Are you sure that you want to delete <strong>{{ literaryformat }}</strong> literary format?</p>
  <em>All books in this format will be also deleted</em>
  <form action="" method="post">
  {% csrf_token %}
    {{ form|crispy}}
    <input class="btn btn-danger" type="submit" value="Yes, delete">
  </form>
{% endblock %}

templates/catalog/literary_format_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Literary Format</h1>
  <form action="" method="post" novalidate>
  {% csrf_token %}
    {{ form|crispy}}
    <input class="btn btn-primary" type="submit" value="Enter">
  </form>
{% endblock %}

templates/catalog/literary_formats_list.html
{% extends "base.html" %}
{% block content %}
  <h1 class="d-flex justify-content-between align-items-center">Literary formats
  <a href="{% url 'catalog:literary-formats-create' %}" class="btn btn-primary">+</a>
  </h1>
  <ul>
  {% if literary_formats_list %}
    <table class="table table-striped">
    <tr>
      <th style="color:black">Name</th>
      <th style="color:black">Update</th>
      <th style="color:black">Delete</th>
    </tr>
      {% for literary_format in literary_formats_list %}
        <tr>
        <td style="color:black">{{ literary_format.name }}</td>
        <td><a href="{% url 'catalog:literary-formats-update' pk=literary_format.id %}">Update</a></td>
        <td><a href="{% url 'catalog:literary-formats-delete' pk=literary_format.id %}">Delete</a></td>
        </tr>
    {% endfor %}
    {% endif %}
    </table>
    <br>
  </ul>
{% endblock %}